<?php

// return [
//     'penjelasan' => [
//         'realistic' => 'Kamu suka bekerja langsung, aktivitas fisik, menggunakan alat dan mesin.',
//         'investigative' => 'Kamu suka menganalisis, meneliti, dan mencari tahu hal baru.',
//         'artistic' => 'Kamu suka mengekspresikan diri, kreatif, dan menyukai keindahan.',
//         'social' => 'Kamu suka membantu orang lain dan nyaman dalam komunikasi.',
//         'enterprising' => 'Kamu percaya diri, suka memimpin dan mengambil keputusan.',
//         'conventional' => 'Kamu menyukai keteraturan, administrasi, dan data.',
//     ],
//     'rekomendasi' => [
//         'realistic' => ['Teknik Mesin', 'Teknik Otomotif', 'Teknik Sipil'],
//         'investigative' => ['Teknik Informatika', 'Analis Kesehatan', 'Bioteknologi'],
//         'artistic' => ['Desain Grafis', 'Seni Musik', 'Multimedia'],
//         'social' => ['Psikologi', 'Keperawatan', 'Pendidikan Guru'],
//         'enterprising' => ['Manajemen', 'Pemasaran', 'Wirausaha'],
//         'conventional' => ['Akuntansi', 'Administrasi Perkantoran', 'Perpajakan'],
//     ]
// ];

// config/riasec.php
return [
    'penjelasan' => [
        'realistic' => 'Kamu suka bekerja langsung, aktivitas fisik, menggunakan alat dan mesin.',
        'investigative' => 'Kamu suka menganalisis, meneliti, dan mencari tahu hal baru.',
        'artistic' => 'Kamu suka mengekspresikan diri, kreatif, dan menyukai keindahan.',
        'social' => 'Kamu suka membantu orang lain dan nyaman dalam komunikasi.',
        'enterprising' => 'Kamu percaya diri, suka memimpin dan mengambil keputusan.',
        'conventional' => 'Kamu menyukai keteraturan, administrasi, dan data.',
    ],

    'jurusan' => [
        'Computer Engineering' => [
            'realistic' => 4,
            'investigative' => 3,
            'artistic' => 1,
            'social' => 1,
            'enterprising' => 2,
            'conventional' => 2,
        ],
        'Arsitec' => [
            'realistic' => 3,
            'investigative' => 2,
            'artistic' => 4,
            'social' => 2,
            'enterprising' => 3,
            'conventional' => 2,
        ],
        'Teknik' => [
            'realistic' => 4,
            'investigative' => 3,
            'artistic' => 1,
            'social' => 1,
            'enterprising' => 2,
            'conventional' => 2,
        ],
        'Akutansi' => [
            'realistic' => 1,
            'investigative' => 2,
            'artistic' => 0,
            'social' => 2,
            'enterprising' => 2,
            'conventional' => 4,
        ],
        'Perpustakaan' => [
            'realistic' => 1,
            'investigative' => 3,
            'artistic' => 2,
            'social' => 4,
            'enterprising' => 1,
            'conventional' => 3,
        ],
        'Matematik' => [
            'realistic' => 2,
            'investigative' => 4,
            'artistic' => 1,
            'social' => 2,
            'enterprising' => 1,
            'conventional' => 3,
        ],
        'Seni' => [
            'realistic' => 2,
            'investigative' => 1,
            'artistic' => 4,
            'social' => 2,
            'enterprising' => 2,
            'conventional' => 1,
        ],
        'DKV' => [
            'realistic' => 3,
            'investigative' => 1,
            'artistic' => 4,
            'social' => 2,
            'enterprising' => 3,
            'conventional' => 1,
        ],
        'Jurnalis' => [
            'realistic' => 1,
            'investigative' => 3,
            'artistic' => 3,
            'social' => 3,
            'enterprising' => 2,
            'conventional' => 2,
        ],
        'Dokter' => [
            'realistic' => 3,
            'investigative' => 4,
            'artistic' => 1,
            'social' => 4,
            'enterprising' => 2,
            'conventional' => 2,
        ],
        'Pendidikan' => [
            'realistic' => 2,
            'investigative' => 2,
            'artistic' => 3,
            'social' => 4,
            'enterprising' => 2,
            'conventional' => 3,
        ],
        'Perawat' => [
            'realistic' => 3,
            'investigative' => 2,
            'artistic' => 1,
            'social' => 4,
            'enterprising' => 2,
            'conventional' =>3,
        ],
        'Bisnis Digital' => [
            'realistic' => 2,
            'investigative' => 2,
            'artistic' => 2,
            'social' => 3,
            'enterprising' => 4,
            'conventional' => 2,
        ],
        'Manajemen' => [
            'realistic' => 1,
            'investigative' => 2,
            'artistic' => 1,
            'social' => 3,
            'enterprising' => 4,
            'conventional' => 3,
        ],
        'Politik' => [
            'realistic' => 1,
            'investigative' => 2,
            'artistic' => 2,
            'social' => 4,
            'enterprising' => 4,
            'conventional' => 2,
        ],
        'Administrasi Perkantoran' => [
            'realistic' => 2,
            'investigative' => 1,
            'artistic' => 0,
            'social' => 3,
            'enterprising' => 2,
            'conventional' => 4,
        ],
        'Statistik' => [
            'realistic' => 2,
            'investigative' => 4,
            'artistic' => 0,
            'social' => 2,
            'enterprising' => 2,
            'conventional' => 3,
        ],
        'Perpajakan' => [
            'realistic' => 1,
            'investigative' => 2,
            'artistic' => 0,
            'social' => 2,
            'enterprising' => 3,
            'conventional' => 4,
        ],
    ],

    //'rekomendasi' => [
      //  'realistic' => ['Teknik Mesin', 'Teknik Otomotif', 'Teknik Sipil'],
        //'investigative' => ['Teknik Informatika', 'Bioteknologi', 'Kedokteran'],
        //'artistic' => ['Desain Grafis', 'DKV', 'Seni Musik'],
        //'social' => ['Psikologi', 'Keperawatan', 'Pendidikan'],
        //'enterprising' => ['Manajemen', 'Wirausaha', 'Marketing'],
        //'conventional' => ['Akuntansi', 'Administrasi', 'Perpajakan'],
    //],
];
